name: Deploy to VPS

on:
  push:
    branches:
      - main  # Adjust this to your main branch name
  workflow_dispatch: 
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
      
    - name: Touch file
      run: "cd ~ && touch file_aftet_gitactions"
