name: Deploy Node app to Production server

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install node js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install NPM depennceies
        run: npm i

      # - name: Syncronize Files to server
      #   run: easingthemes/ssh-deploy@v2.1.5
      #   env: 
      #     SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
      #     SOURCE: "."
      #     REMOTE_HOST: ${{ secrets.VPS_HOST }}
      #     REMOTE_USER: ${{ secrets.VPS_USER }}
      #     TARGET: "/var/www/html"

      - name: Run Remote/Astisan Comands
        uses: appleboy/ssh-action@v0.1.6
        with: 
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          script: "cd /var/www/html && touch this_is_github_stuf"
          
        
